

void Roulette_Stairs_DOWN_digital(int x, int y) {       // 下方向へルーレットのようにLEDが点灯し、
                                          // 常時点灯しているLEDが最下段から徐々に増えていく
                                          // x [ms] = LEDが全て点灯してからの待機時間
                                          // y [ms] = 次のLEDを点灯させるまでの間隔
                                          // 
                                          //
                                          // 指標値① 高速 Roulette_Stairs(10000, 30);
                                          // 指標値② 中速 Roulette_Stairs(10000, 50);
                                          // 指標値③ 低速 Roulette_Stairs(10000, 100);
                      

    digitalWrite(LED14, HIGH);
    delay(y);
    digitalWrite(LED14, LOW);
    delay(y);
    digitalWrite(LED13, HIGH);
    delay(y);
    digitalWrite(LED13, LOW);
    delay(y);
    digitalWrite(LED12, HIGH);
    delay(y);
    digitalWrite(LED12, LOW);
    delay(y);
    digitalWrite(LED11, HIGH);
    delay(y);
    digitalWrite(LED11, LOW);
    delay(y);
    digitalWrite(LED10, HIGH);
    delay(y);
    digitalWrite(LED10, LOW);
    delay(y);
    digitalWrite(LED9, HIGH);
    delay(y);
    digitalWrite(LED9, LOW);
    delay(y);
    digitalWrite(LED8, HIGH);
    delay(y);
    digitalWrite(LED8, LOW);
    delay(y);
    digitalWrite(LED7, HIGH);
    delay(y);
    digitalWrite(LED7, LOW);
    delay(y);
    digitalWrite(LED6, HIGH);
    delay(y);
    digitalWrite(LED6, LOW);
    delay(y);
    digitalWrite(LED5, HIGH);
    delay(y);
    digitalWrite(LED5, LOW);
    delay(y);
    digitalWrite(LED4, HIGH);
    delay(y);
    digitalWrite(LED4, LOW);
    delay(y);
    digitalWrite(LED3, HIGH);
    delay(y);
    digitalWrite(LED3, LOW);
    delay(y);
    digitalWrite(LED2, HIGH);
    delay(y);
    digitalWrite(LED2, LOW);
    delay(y);
    digitalWrite(LED1, HIGH);    // LED1(最下段)のみ点灯したままにして、最上段からLEDを再び点灯させる。
    delay(y);

    digitalWrite(LED14, HIGH);
    delay(y);
    digitalWrite(LED14, LOW);
    delay(y);
    digitalWrite(LED13, HIGH);
    delay(y);
    digitalWrite(LED13, LOW);
    delay(y);
    digitalWrite(LED12, HIGH);
    delay(y);
    digitalWrite(LED12, LOW);
    delay(y);
    digitalWrite(LED11, HIGH);
    delay(y);
    digitalWrite(LED11, LOW);
    delay(y);
    digitalWrite(LED10, HIGH);
    delay(y);
    digitalWrite(LED10, LOW);
    delay(y);
    digitalWrite(LED9, HIGH);
    delay(y);
    digitalWrite(LED9, LOW);
    delay(y);
    digitalWrite(LED8, HIGH);
    delay(y);
    digitalWrite(LED8, LOW);
    delay(y);
    digitalWrite(LED7, HIGH);
    delay(y);
    digitalWrite(LED7, LOW);
    delay(y);
    digitalWrite(LED6, HIGH);
    delay(y);
    digitalWrite(LED6, LOW);
    delay(y);
    digitalWrite(LED5, HIGH);
    delay(y);
    digitalWrite(LED5, LOW);
    delay(y);
    digitalWrite(LED4, HIGH);
    delay(y);
    digitalWrite(LED4, LOW);
    delay(y);
    digitalWrite(LED3, HIGH);
    delay(y);
    digitalWrite(LED3, LOW);
    delay(y);
    digitalWrite(LED2, HIGH);
    delay(y);

    digitalWrite(LED14, HIGH);
    delay(y);
    digitalWrite(LED14, LOW);
    delay(y);
    digitalWrite(LED13, HIGH);
    delay(y);
    digitalWrite(LED13, LOW);
    delay(y);
    digitalWrite(LED12, HIGH);
    delay(y);
    digitalWrite(LED12, LOW);
    delay(y);
    digitalWrite(LED11, HIGH);
    delay(y);
    digitalWrite(LED11, LOW);
    delay(y);
    digitalWrite(LED10, HIGH);
    delay(y);
    digitalWrite(LED10, LOW);
    delay(y);
    digitalWrite(LED9, HIGH);
    delay(y);
    digitalWrite(LED9, LOW);
    delay(y);
    digitalWrite(LED8, HIGH);
    delay(y);
    digitalWrite(LED8, LOW);
    delay(y);
    digitalWrite(LED7, HIGH);
    delay(y);
    digitalWrite(LED7, LOW);
    delay(y);
    digitalWrite(LED6, HIGH);
    delay(y);
    digitalWrite(LED6, LOW);
    delay(y);
    digitalWrite(LED5, HIGH);
    delay(y);
    digitalWrite(LED5, LOW);
    delay(y);
    digitalWrite(LED4, HIGH);
    delay(y);
    digitalWrite(LED4, LOW);
    delay(y);
    digitalWrite(LED3, HIGH);
    delay(y);

    digitalWrite(LED14, HIGH);
    delay(y);
    digitalWrite(LED14, LOW);
    delay(y);
    digitalWrite(LED13, HIGH);
    delay(y);
    digitalWrite(LED13, LOW);
    delay(y);
    digitalWrite(LED12, HIGH);
    delay(y);
    digitalWrite(LED12, LOW);
    delay(y);
    digitalWrite(LED11, HIGH);
    delay(y);
    digitalWrite(LED11, LOW);
    delay(y);
    digitalWrite(LED10, HIGH);
    delay(y);
    digitalWrite(LED10, LOW);
    delay(y);
    digitalWrite(LED9, HIGH);
    delay(y);
    digitalWrite(LED9, LOW);
    delay(y);
    digitalWrite(LED8, HIGH);
    delay(y);
    digitalWrite(LED8, LOW);
    delay(y);
    digitalWrite(LED7, HIGH);
    delay(y);
    digitalWrite(LED7, LOW);
    delay(y);
    digitalWrite(LED6, HIGH);
    delay(y);
    digitalWrite(LED6, LOW);
    delay(y);
    digitalWrite(LED5, HIGH);
    delay(y);
    digitalWrite(LED5, LOW);
    delay(y);
    digitalWrite(LED4, HIGH);
    delay(y);

    digitalWrite(LED14, HIGH);
    delay(y);
    digitalWrite(LED14, LOW);
    delay(y);
    digitalWrite(LED13, HIGH);
    delay(y);
    digitalWrite(LED13, LOW);
    delay(y);
    digitalWrite(LED12, HIGH);
    delay(y);
    digitalWrite(LED12, LOW);
    delay(y);
    digitalWrite(LED11, HIGH);
    delay(y);
    digitalWrite(LED11, LOW);
    delay(y);
    digitalWrite(LED10, HIGH);
    delay(y);
    digitalWrite(LED10, LOW);
    delay(y);
    digitalWrite(LED9, HIGH);
    delay(y);
    digitalWrite(LED9, LOW);
    delay(y);
    digitalWrite(LED8, HIGH);
    delay(y);
    digitalWrite(LED8, LOW);
    delay(y);
    digitalWrite(LED7, HIGH);
    delay(y);
    digitalWrite(LED7, LOW);
    delay(y);
    digitalWrite(LED6, HIGH);
    delay(y);
    digitalWrite(LED6, LOW);
    delay(y);
    digitalWrite(LED5, HIGH);
    delay(y);

    digitalWrite(LED14, HIGH);
    delay(y);
    digitalWrite(LED14, LOW);
    delay(y);
    digitalWrite(LED13, HIGH);
    delay(y);
    digitalWrite(LED13, LOW);
    delay(y);
    digitalWrite(LED12, HIGH);
    delay(y);
    digitalWrite(LED12, LOW);
    delay(y);
    digitalWrite(LED11, HIGH);
    delay(y);
    digitalWrite(LED11, LOW);
    delay(y);
    digitalWrite(LED10, HIGH);
    delay(y);
    digitalWrite(LED10, LOW);
    delay(y);
    digitalWrite(LED9, HIGH);
    delay(y);
    digitalWrite(LED9, LOW);
    delay(y);
    digitalWrite(LED8, HIGH);
    delay(y);
    digitalWrite(LED8, LOW);
    delay(y);
    digitalWrite(LED7, HIGH);
    delay(y);
    digitalWrite(LED7, LOW);
    delay(y);
    digitalWrite(LED6, HIGH);
    delay(y);

    digitalWrite(LED14, HIGH);
    delay(y);
    digitalWrite(LED14, LOW);
    delay(y);
    digitalWrite(LED13, HIGH);
    delay(y);
    digitalWrite(LED13, LOW);
    delay(y);
    digitalWrite(LED12, HIGH);
    delay(y);
    digitalWrite(LED12, LOW);
    delay(y);
    digitalWrite(LED11, HIGH);
    delay(y);
    digitalWrite(LED11, LOW);
    delay(y);
    digitalWrite(LED10, HIGH);
    delay(y);
    digitalWrite(LED10, LOW);
    delay(y);
    digitalWrite(LED9, HIGH);
    delay(y);
    digitalWrite(LED9, LOW);
    delay(y);
    digitalWrite(LED8, HIGH);
    delay(y);
    digitalWrite(LED8, LOW);
    delay(y);
    digitalWrite(LED7, HIGH);
    delay(y);

    digitalWrite(LED14, HIGH);
    delay(y);
    digitalWrite(LED14, LOW);
    delay(y);
    digitalWrite(LED13, HIGH);
    delay(y);
    digitalWrite(LED13, LOW);
    delay(y);
    digitalWrite(LED12, HIGH);
    delay(y);
    digitalWrite(LED12, LOW);
    delay(y);
    digitalWrite(LED11, HIGH);
    delay(y);
    digitalWrite(LED11, LOW);
    delay(y);
    digitalWrite(LED10, HIGH);
    delay(y);
    digitalWrite(LED10, LOW);
    delay(y);
    digitalWrite(LED9, HIGH);
    delay(y);
    digitalWrite(LED9, LOW);
    delay(y);
    digitalWrite(LED8, HIGH);
    delay(y);

    digitalWrite(LED14, HIGH);
    delay(y);
    digitalWrite(LED14, LOW);
    delay(y);
    digitalWrite(LED13, HIGH);
    delay(y);
    digitalWrite(LED13, LOW);
    delay(y);
    digitalWrite(LED12, HIGH);
    delay(y);
    digitalWrite(LED12, LOW);
    delay(y);
    digitalWrite(LED11, HIGH);
    delay(y);
    digitalWrite(LED11, LOW);
    delay(y);
    digitalWrite(LED10, HIGH);
    delay(y);
    digitalWrite(LED10, LOW);
    delay(y);
    digitalWrite(LED9, HIGH);
    delay(y);

    digitalWrite(LED14, HIGH);
    delay(y);
    digitalWrite(LED14, LOW);
    delay(y);
    digitalWrite(LED13, HIGH);
    delay(y);
    digitalWrite(LED13, LOW);
    delay(y);
    digitalWrite(LED12, HIGH);
    delay(y);
    digitalWrite(LED12, LOW);
    delay(y);
    digitalWrite(LED11, HIGH);
    delay(y);
    digitalWrite(LED11, LOW);
    delay(y);
    digitalWrite(LED10, HIGH);
    delay(y);

    digitalWrite(LED14, HIGH);
    delay(y);
    digitalWrite(LED14, LOW);
    delay(y);
    digitalWrite(LED13, HIGH);
    delay(y);
    digitalWrite(LED13, LOW);
    delay(y);
    digitalWrite(LED12, HIGH);
    delay(y);
    digitalWrite(LED12, LOW);
    delay(y);
    digitalWrite(LED11, HIGH);
    delay(y);

    digitalWrite(LED14, HIGH);
    delay(y);
    digitalWrite(LED14, LOW);
    delay(y);
    digitalWrite(LED13, HIGH);
    delay(y);
    digitalWrite(LED13, LOW);
    delay(y);
    digitalWrite(LED12, HIGH);
    delay(y);

    digitalWrite(LED14, HIGH);
    delay(y);
    digitalWrite(LED13, HIGH);
    delay(y);
    
    digitalWrite(LED14, HIGH);
    delay(y);
    
    delay(x);

    digitalWrite(LED1,LOW);
    digitalWrite(LED2,LOW);
    digitalWrite(LED3,LOW);
    digitalWrite(LED4,LOW);
    digitalWrite(LED5,LOW);
    digitalWrite(LED6,LOW);
    digitalWrite(LED7,LOW);
    digitalWrite(LED8,LOW);
    digitalWrite(LED9,LOW);
    digitalWrite(LED10,LOW);
    digitalWrite(LED11,LOW);
    digitalWrite(LED12,LOW);
    digitalWrite(LED13,LOW);
    digitalWrite(LED14,LOW); 
}
